# Generated by Django 3.0.6 on 2020-05-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='user_default.jpg', null=True, upload_to='users/pictures'),
        ),
    ]
